package app.dao;

import app.entity.bill;
import app.entity.billExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface billMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..bill
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    int countByExample(billExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..bill
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    int deleteByExample(billExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..bill
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    int deleteByPrimaryKey(Integer billid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..bill
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    int insert(bill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..bill
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    int insertSelective(bill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..bill
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    List<bill> selectByExample(billExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..bill
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    bill selectByPrimaryKey(Integer billid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..bill
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") bill record, @Param("example") billExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..bill
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    int updateByExample(@Param("record") bill record, @Param("example") billExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..bill
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    int updateByPrimaryKeySelective(bill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..bill
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    int updateByPrimaryKey(bill record);
}