package app.dao;

import app.entity.roomStatis;
import app.entity.roomStatisExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface roomStatisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..roomstatis
     *
     * @mbggenerated Sat May 25 19:20:51 CST 2019
     */
    int countByExample(roomStatisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..roomstatis
     *
     * @mbggenerated Sat May 25 19:20:51 CST 2019
     */
    int deleteByExample(roomStatisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..roomstatis
     *
     * @mbggenerated Sat May 25 19:20:51 CST 2019
     */
    int deleteByPrimaryKey(Integer roomid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..roomstatis
     *
     * @mbggenerated Sat May 25 19:20:51 CST 2019
     */
    int insert(roomStatis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..roomstatis
     *
     * @mbggenerated Sat May 25 19:20:51 CST 2019
     */
    int insertSelective(roomStatis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..roomstatis
     *
     * @mbggenerated Sat May 25 19:20:51 CST 2019
     */
    List<roomStatis> selectByExample(roomStatisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..roomstatis
     *
     * @mbggenerated Sat May 25 19:20:51 CST 2019
     */
    roomStatis selectByPrimaryKey(Integer roomid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..roomstatis
     *
     * @mbggenerated Sat May 25 19:20:51 CST 2019
     */
    int updateByExampleSelective(@Param("record") roomStatis record, @Param("example") roomStatisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..roomstatis
     *
     * @mbggenerated Sat May 25 19:20:51 CST 2019
     */
    int updateByExample(@Param("record") roomStatis record, @Param("example") roomStatisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..roomstatis
     *
     * @mbggenerated Sat May 25 19:20:51 CST 2019
     */
    int updateByPrimaryKeySelective(roomStatis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..roomstatis
     *
     * @mbggenerated Sat May 25 19:20:51 CST 2019
     */
    int updateByPrimaryKey(roomStatis record);
}