package app.dao;

import app.entity.serviceDetail;
import app.entity.serviceDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface serviceDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..servicedetail
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    int countByExample(serviceDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..servicedetail
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    int deleteByExample(serviceDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..servicedetail
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    int deleteByPrimaryKey(Integer servicedetailid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..servicedetail
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    int insert(serviceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..servicedetail
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    int insertSelective(serviceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..servicedetail
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    List<serviceDetail> selectByExample(serviceDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..servicedetail
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    serviceDetail selectByPrimaryKey(Integer servicedetailid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..servicedetail
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") serviceDetail record, @Param("example") serviceDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..servicedetail
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    int updateByExample(@Param("record") serviceDetail record, @Param("example") serviceDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..servicedetail
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    int updateByPrimaryKeySelective(serviceDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table distributedairconditioner..servicedetail
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    int updateByPrimaryKey(serviceDetail record);
}