package app.entity;

public class bill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..bill.billId
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    private Integer billid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..bill.startTime
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    private String starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..bill.stopTime
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    private String stoptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..bill.roomId
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    private Integer roomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..bill.userId
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..bill.totalFee
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    private Double totalfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..bill.runningTime
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    private Integer runningtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..bill.scheduleCounter
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    private Integer schedulecounter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..bill.detailedRecordCounter
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    private Integer detailedrecordcounter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..bill.powerOnCounter
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    private Integer poweroncounter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..bill.ChangeTempCounter
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    private Integer changetempcounter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..bill.ChangeFunCounter
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    private Integer changefuncounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..bill.billId
     *
     * @return the value of distributedairconditioner..bill.billId
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public Integer getBillid() {
        return billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..bill.billId
     *
     * @param billid the value for distributedairconditioner..bill.billId
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public void setBillid(Integer billid) {
        this.billid = billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..bill.startTime
     *
     * @return the value of distributedairconditioner..bill.startTime
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..bill.startTime
     *
     * @param starttime the value for distributedairconditioner..bill.startTime
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime == null ? null : starttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..bill.stopTime
     *
     * @return the value of distributedairconditioner..bill.stopTime
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public String getStoptime() {
        return stoptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..bill.stopTime
     *
     * @param stoptime the value for distributedairconditioner..bill.stopTime
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public void setStoptime(String stoptime) {
        this.stoptime = stoptime == null ? null : stoptime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..bill.roomId
     *
     * @return the value of distributedairconditioner..bill.roomId
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public Integer getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..bill.roomId
     *
     * @param roomid the value for distributedairconditioner..bill.roomId
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..bill.userId
     *
     * @return the value of distributedairconditioner..bill.userId
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..bill.userId
     *
     * @param userid the value for distributedairconditioner..bill.userId
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..bill.totalFee
     *
     * @return the value of distributedairconditioner..bill.totalFee
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public Double getTotalfee() {
        return totalfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..bill.totalFee
     *
     * @param totalfee the value for distributedairconditioner..bill.totalFee
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public void setTotalfee(Double totalfee) {
        this.totalfee = totalfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..bill.runningTime
     *
     * @return the value of distributedairconditioner..bill.runningTime
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public Integer getRunningtime() {
        return runningtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..bill.runningTime
     *
     * @param runningtime the value for distributedairconditioner..bill.runningTime
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public void setRunningtime(Integer runningtime) {
        this.runningtime = runningtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..bill.scheduleCounter
     *
     * @return the value of distributedairconditioner..bill.scheduleCounter
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public Integer getSchedulecounter() {
        return schedulecounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..bill.scheduleCounter
     *
     * @param schedulecounter the value for distributedairconditioner..bill.scheduleCounter
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public void setSchedulecounter(Integer schedulecounter) {
        this.schedulecounter = schedulecounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..bill.detailedRecordCounter
     *
     * @return the value of distributedairconditioner..bill.detailedRecordCounter
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public Integer getDetailedrecordcounter() {
        return detailedrecordcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..bill.detailedRecordCounter
     *
     * @param detailedrecordcounter the value for distributedairconditioner..bill.detailedRecordCounter
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public void setDetailedrecordcounter(Integer detailedrecordcounter) {
        this.detailedrecordcounter = detailedrecordcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..bill.powerOnCounter
     *
     * @return the value of distributedairconditioner..bill.powerOnCounter
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public Integer getPoweroncounter() {
        return poweroncounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..bill.powerOnCounter
     *
     * @param poweroncounter the value for distributedairconditioner..bill.powerOnCounter
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public void setPoweroncounter(Integer poweroncounter) {
        this.poweroncounter = poweroncounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..bill.ChangeTempCounter
     *
     * @return the value of distributedairconditioner..bill.ChangeTempCounter
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public Integer getChangetempcounter() {
        return changetempcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..bill.ChangeTempCounter
     *
     * @param changetempcounter the value for distributedairconditioner..bill.ChangeTempCounter
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public void setChangetempcounter(Integer changetempcounter) {
        this.changetempcounter = changetempcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..bill.ChangeFunCounter
     *
     * @return the value of distributedairconditioner..bill.ChangeFunCounter
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public Integer getChangefuncounter() {
        return changefuncounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..bill.ChangeFunCounter
     *
     * @param changefuncounter the value for distributedairconditioner..bill.ChangeFunCounter
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public void setChangefuncounter(Integer changefuncounter) {
        this.changefuncounter = changefuncounter;
    }
}