package app.entity;

public class bill {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..bill.billId
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    private Integer billid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..bill.startTime
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    private String starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..bill.stopTime
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    private String stoptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..bill.roomId
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    private Integer roomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..bill.userId
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..bill.billFee
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    private Float billfee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..bill.billId
     *
     * @return the value of distributedairconditioner..bill.billId
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public Integer getBillid() {
        return billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..bill.billId
     *
     * @param billid the value for distributedairconditioner..bill.billId
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public void setBillid(Integer billid) {
        this.billid = billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..bill.startTime
     *
     * @return the value of distributedairconditioner..bill.startTime
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..bill.startTime
     *
     * @param starttime the value for distributedairconditioner..bill.startTime
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime == null ? null : starttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..bill.stopTime
     *
     * @return the value of distributedairconditioner..bill.stopTime
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public String getStoptime() {
        return stoptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..bill.stopTime
     *
     * @param stoptime the value for distributedairconditioner..bill.stopTime
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public void setStoptime(String stoptime) {
        this.stoptime = stoptime == null ? null : stoptime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..bill.roomId
     *
     * @return the value of distributedairconditioner..bill.roomId
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public Integer getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..bill.roomId
     *
     * @param roomid the value for distributedairconditioner..bill.roomId
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..bill.userId
     *
     * @return the value of distributedairconditioner..bill.userId
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..bill.userId
     *
     * @param userid the value for distributedairconditioner..bill.userId
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..bill.billFee
     *
     * @return the value of distributedairconditioner..bill.billFee
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public Float getBillfee() {
        return billfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..bill.billFee
     *
     * @param billfee the value for distributedairconditioner..bill.billFee
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public void setBillfee(Float billfee) {
        this.billfee = billfee;
    }
}