package app.entity;

public class roomStatis {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..roomstatis.roomId
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    private Integer roomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..roomstatis.turnOnCounter
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    private Integer turnoncounter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..roomstatis.runningTime
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    private Integer runningtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..roomstatis.totalServiceCount
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    private Integer totalservicecount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..roomstatis.billCounter
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    private Float billcounter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..roomstatis.ChangeTermCounter
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    private Integer changetermcounter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..roomstatis.ChangeFunCounter
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    private Integer changefuncounter;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..roomstatis.roomId
     *
     * @return the value of distributedairconditioner..roomstatis.roomId
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public Integer getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..roomstatis.roomId
     *
     * @param roomid the value for distributedairconditioner..roomstatis.roomId
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..roomstatis.turnOnCounter
     *
     * @return the value of distributedairconditioner..roomstatis.turnOnCounter
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public Integer getTurnoncounter() {
        return turnoncounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..roomstatis.turnOnCounter
     *
     * @param turnoncounter the value for distributedairconditioner..roomstatis.turnOnCounter
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public void setTurnoncounter(Integer turnoncounter) {
        this.turnoncounter = turnoncounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..roomstatis.runningTime
     *
     * @return the value of distributedairconditioner..roomstatis.runningTime
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public Integer getRunningtime() {
        return runningtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..roomstatis.runningTime
     *
     * @param runningtime the value for distributedairconditioner..roomstatis.runningTime
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public void setRunningtime(Integer runningtime) {
        this.runningtime = runningtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..roomstatis.totalServiceCount
     *
     * @return the value of distributedairconditioner..roomstatis.totalServiceCount
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public Integer getTotalservicecount() {
        return totalservicecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..roomstatis.totalServiceCount
     *
     * @param totalservicecount the value for distributedairconditioner..roomstatis.totalServiceCount
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public void setTotalservicecount(Integer totalservicecount) {
        this.totalservicecount = totalservicecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..roomstatis.billCounter
     *
     * @return the value of distributedairconditioner..roomstatis.billCounter
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public Float getBillcounter() {
        return billcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..roomstatis.billCounter
     *
     * @param billcounter the value for distributedairconditioner..roomstatis.billCounter
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public void setBillcounter(Float billcounter) {
        this.billcounter = billcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..roomstatis.ChangeTermCounter
     *
     * @return the value of distributedairconditioner..roomstatis.ChangeTermCounter
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public Integer getChangetermcounter() {
        return changetermcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..roomstatis.ChangeTermCounter
     *
     * @param changetermcounter the value for distributedairconditioner..roomstatis.ChangeTermCounter
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public void setChangetermcounter(Integer changetermcounter) {
        this.changetermcounter = changetermcounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..roomstatis.ChangeFunCounter
     *
     * @return the value of distributedairconditioner..roomstatis.ChangeFunCounter
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public Integer getChangefuncounter() {
        return changefuncounter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..roomstatis.ChangeFunCounter
     *
     * @param changefuncounter the value for distributedairconditioner..roomstatis.ChangeFunCounter
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public void setChangefuncounter(Integer changefuncounter) {
        this.changefuncounter = changefuncounter;
    }
}