package app.entity;

public class serviceDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..servicedetail.serviceId
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    private Integer serviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..servicedetail.startTime
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    private String starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..servicedetail.stopTime
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    private String stoptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..servicedetail.roomId
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    private Integer roomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..servicedetail.billId
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    private Integer billid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..servicedetail.FunSpeed
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    private Integer funspeed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..servicedetail.serviceId
     *
     * @return the value of distributedairconditioner..servicedetail.serviceId
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public Integer getServiceid() {
        return serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..servicedetail.serviceId
     *
     * @param serviceid the value for distributedairconditioner..servicedetail.serviceId
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public void setServiceid(Integer serviceid) {
        this.serviceid = serviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..servicedetail.startTime
     *
     * @return the value of distributedairconditioner..servicedetail.startTime
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..servicedetail.startTime
     *
     * @param starttime the value for distributedairconditioner..servicedetail.startTime
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime == null ? null : starttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..servicedetail.stopTime
     *
     * @return the value of distributedairconditioner..servicedetail.stopTime
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public String getStoptime() {
        return stoptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..servicedetail.stopTime
     *
     * @param stoptime the value for distributedairconditioner..servicedetail.stopTime
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public void setStoptime(String stoptime) {
        this.stoptime = stoptime == null ? null : stoptime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..servicedetail.roomId
     *
     * @return the value of distributedairconditioner..servicedetail.roomId
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public Integer getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..servicedetail.roomId
     *
     * @param roomid the value for distributedairconditioner..servicedetail.roomId
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..servicedetail.billId
     *
     * @return the value of distributedairconditioner..servicedetail.billId
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public Integer getBillid() {
        return billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..servicedetail.billId
     *
     * @param billid the value for distributedairconditioner..servicedetail.billId
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public void setBillid(Integer billid) {
        this.billid = billid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..servicedetail.FunSpeed
     *
     * @return the value of distributedairconditioner..servicedetail.FunSpeed
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public Integer getFunspeed() {
        return funspeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..servicedetail.FunSpeed
     *
     * @param funspeed the value for distributedairconditioner..servicedetail.FunSpeed
     *
     * @mbggenerated Sat May 25 20:12:55 CST 2019
     */
    public void setFunspeed(Integer funspeed) {
        this.funspeed = funspeed;
    }
}