package app.entity;

public class serviceDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..servicedetail.serviceDetailId
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    private Integer servicedetailid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..servicedetail.startTime
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    private String starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..servicedetail.stopTime
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    private String stoptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..servicedetail.roomId
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    private Integer roomid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..servicedetail.funSpeed
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    private String funspeed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..servicedetail.feeRate
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    private Double feerate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..servicedetail.fee
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    private Double fee;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..servicedetail.serviceDetailId
     *
     * @return the value of distributedairconditioner..servicedetail.serviceDetailId
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public Integer getServicedetailid() {
        return servicedetailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..servicedetail.serviceDetailId
     *
     * @param servicedetailid the value for distributedairconditioner..servicedetail.serviceDetailId
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public void setServicedetailid(Integer servicedetailid) {
        this.servicedetailid = servicedetailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..servicedetail.startTime
     *
     * @return the value of distributedairconditioner..servicedetail.startTime
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..servicedetail.startTime
     *
     * @param starttime the value for distributedairconditioner..servicedetail.startTime
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime == null ? null : starttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..servicedetail.stopTime
     *
     * @return the value of distributedairconditioner..servicedetail.stopTime
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public String getStoptime() {
        return stoptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..servicedetail.stopTime
     *
     * @param stoptime the value for distributedairconditioner..servicedetail.stopTime
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public void setStoptime(String stoptime) {
        this.stoptime = stoptime == null ? null : stoptime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..servicedetail.roomId
     *
     * @return the value of distributedairconditioner..servicedetail.roomId
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public Integer getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..servicedetail.roomId
     *
     * @param roomid the value for distributedairconditioner..servicedetail.roomId
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..servicedetail.funSpeed
     *
     * @return the value of distributedairconditioner..servicedetail.funSpeed
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public String getFunspeed() {
        return funspeed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..servicedetail.funSpeed
     *
     * @param funspeed the value for distributedairconditioner..servicedetail.funSpeed
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public void setFunspeed(String funspeed) {
        this.funspeed = funspeed == null ? null : funspeed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..servicedetail.feeRate
     *
     * @return the value of distributedairconditioner..servicedetail.feeRate
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public Double getFeerate() {
        return feerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..servicedetail.feeRate
     *
     * @param feerate the value for distributedairconditioner..servicedetail.feeRate
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public void setFeerate(Double feerate) {
        this.feerate = feerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..servicedetail.fee
     *
     * @return the value of distributedairconditioner..servicedetail.fee
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public Double getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..servicedetail.fee
     *
     * @param fee the value for distributedairconditioner..servicedetail.fee
     *
     * @mbggenerated Sun May 26 02:41:16 CST 2019
     */
    public void setFee(Double fee) {
        this.fee = fee;
    }
}