package app.entity;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..user.userId
     *
     * @mbggenerated Sat May 25 20:33:34 CST 2019
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..user.userName
     *
     * @mbggenerated Sat May 25 20:33:34 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..user.password
     *
     * @mbggenerated Sat May 25 20:33:34 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column distributedairconditioner..user.startTime
     *
     * @mbggenerated Sat May 25 20:33:34 CST 2019
     */
    private String starttime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..user.userId
     *
     * @return the value of distributedairconditioner..user.userId
     *
     * @mbggenerated Sat May 25 20:33:34 CST 2019
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..user.userId
     *
     * @param userid the value for distributedairconditioner..user.userId
     *
     * @mbggenerated Sat May 25 20:33:34 CST 2019
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..user.userName
     *
     * @return the value of distributedairconditioner..user.userName
     *
     * @mbggenerated Sat May 25 20:33:34 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..user.userName
     *
     * @param username the value for distributedairconditioner..user.userName
     *
     * @mbggenerated Sat May 25 20:33:34 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..user.password
     *
     * @return the value of distributedairconditioner..user.password
     *
     * @mbggenerated Sat May 25 20:33:34 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..user.password
     *
     * @param password the value for distributedairconditioner..user.password
     *
     * @mbggenerated Sat May 25 20:33:34 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column distributedairconditioner..user.startTime
     *
     * @return the value of distributedairconditioner..user.startTime
     *
     * @mbggenerated Sat May 25 20:33:34 CST 2019
     */
    public String getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column distributedairconditioner..user.startTime
     *
     * @param starttime the value for distributedairconditioner..user.startTime
     *
     * @mbggenerated Sat May 25 20:33:34 CST 2019
     */
    public void setStarttime(String starttime) {
        this.starttime = starttime == null ? null : starttime.trim();
    }
}